// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: interaction/interaction.proto

package interaction

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LikeItem structure based on domain model
type LikeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	LikedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=liked_at,json=likedAt,proto3" json:"liked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeItem) Reset() {
	*x = LikeItem{}
	mi := &file_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeItem) ProtoMessage() {}

func (x *LikeItem) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeItem.ProtoReflect.Descriptor instead.
func (*LikeItem) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeItem) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeItem) GetLikedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LikedAt
	}
	return nil
}

// CommentItem structure based on domain model
type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0 for root comment
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`       // Materialized path
	Replies       []*CommentItem         `protobuf:"bytes,8,rep,name=replies,proto3" json:"replies,omitempty"` // Nested replies for hierarchical display
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *CommentItem) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentItem) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommentItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommentItem) GetReplies() []*CommentItem {
	if x != nil {
		return x.Replies
	}
	return nil
}

// FavoriteItem structure based on domain model
type FavoriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FavoritedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=favorited_at,json=favoritedAt,proto3" json:"favorited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteItem) Reset() {
	*x = FavoriteItem{}
	mi := &file_interaction_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteItem) ProtoMessage() {}

func (x *FavoriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteItem.ProtoReflect.Descriptor instead.
func (*FavoriteItem) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *FavoriteItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteItem) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *FavoriteItem) GetFavoritedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FavoritedAt
	}
	return nil
}

// Requests and Replies for Like/Unlike
type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *LikeVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type LikeVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoReply) Reset() {
	*x = LikeVideoReply{}
	mi := &file_interaction_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoReply) ProtoMessage() {}

func (x *LikeVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoReply.ProtoReflect.Descriptor instead.
func (*LikeVideoReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *LikeVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoRequest) Reset() {
	*x = UnlikeVideoRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoRequest) ProtoMessage() {}

func (x *UnlikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoRequest.ProtoReflect.Descriptor instead.
func (*UnlikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *UnlikeVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnlikeVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoReply) Reset() {
	*x = UnlikeVideoReply{}
	mi := &file_interaction_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoReply) ProtoMessage() {}

func (x *UnlikeVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoReply.ProtoReflect.Descriptor instead.
func (*UnlikeVideoReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *UnlikeVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetVideoLikeCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoLikeCountRequest) Reset() {
	*x = GetVideoLikeCountRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoLikeCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountRequest) ProtoMessage() {}

func (x *GetVideoLikeCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountRequest.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoLikeCountRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoLikeCountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoLikeCountReply) Reset() {
	*x = GetVideoLikeCountReply{}
	mi := &file_interaction_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoLikeCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountReply) ProtoMessage() {}

func (x *GetVideoLikeCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountReply.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetVideoLikeCountReply) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

// Requests and Replies for Comments
type PostCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0 for root comment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentRequest) Reset() {
	*x = PostCommentRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentRequest) ProtoMessage() {}

func (x *PostCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentRequest.ProtoReflect.Descriptor instead.
func (*PostCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *PostCommentRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *PostCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type PostCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentItem           `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReply) Reset() {
	*x = PostCommentReply{}
	mi := &file_interaction_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReply) ProtoMessage() {}

func (x *PostCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReply.ProtoReflect.Descriptor instead.
func (*PostCommentReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *PostCommentReply) GetComment() *CommentItem {
	if x != nil {
		return x.Comment
	}
	return nil
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                     // Page number (e.g., 1-based)
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                  // Number of comments per page
	RootCommentId int64                  `protobuf:"varint,4,opt,name=root_comment_id,json=rootCommentId,proto3" json:"root_comment_id,omitempty"` // Optional: List replies for a specific root comment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommentsRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ListCommentsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetRootCommentId() int64 {
	if x != nil {
		return x.RootCommentId
	}
	return 0
}

type ListCommentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentItem         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`          // Total number of pages
	TotalComments int64                  `protobuf:"varint,3,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"` // Total number of comments (for the video or root comment)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReply) Reset() {
	*x = ListCommentsReply{}
	mi := &file_interaction_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReply) ProtoMessage() {}

func (x *ListCommentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReply.ProtoReflect.Descriptor instead.
func (*ListCommentsReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *ListCommentsReply) GetComments() []*CommentItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListCommentsReply) GetTotalComments() int64 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

// Requests and Replies for Favorites
type FavoriteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteVideoRequest) Reset() {
	*x = FavoriteVideoRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoRequest) ProtoMessage() {}

func (x *FavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*FavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *FavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type FavoriteVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteVideoReply) Reset() {
	*x = FavoriteVideoReply{}
	mi := &file_interaction_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoReply) ProtoMessage() {}

func (x *FavoriteVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoReply.ProtoReflect.Descriptor instead.
func (*FavoriteVideoReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *FavoriteVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnfavoriteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteVideoRequest) Reset() {
	*x = UnfavoriteVideoRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteVideoRequest) ProtoMessage() {}

func (x *UnfavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*UnfavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *UnfavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnfavoriteVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteVideoReply) Reset() {
	*x = UnfavoriteVideoReply{}
	mi := &file_interaction_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteVideoReply) ProtoMessage() {}

func (x *UnfavoriteVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteVideoReply.ProtoReflect.Descriptor instead.
func (*UnfavoriteVideoReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *UnfavoriteVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoritesRequest) Reset() {
	*x = ListFavoritesRequest{}
	mi := &file_interaction_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesRequest) ProtoMessage() {}

func (x *ListFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *ListFavoritesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFavoritesRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListFavoritesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFavoritesReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Favorites      []*FavoriteItem        `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	TotalPages     int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalFavorites int64                  `protobuf:"varint,3,opt,name=total_favorites,json=totalFavorites,proto3" json:"total_favorites,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFavoritesReply) Reset() {
	*x = ListFavoritesReply{}
	mi := &file_interaction_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoritesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoritesReply) ProtoMessage() {}

func (x *ListFavoritesReply) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoritesReply.ProtoReflect.Descriptor instead.
func (*ListFavoritesReply) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *ListFavoritesReply) GetFavorites() []*FavoriteItem {
	if x != nil {
		return x.Favorites
	}
	return nil
}

func (x *ListFavoritesReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListFavoritesReply) GetTotalFavorites() int64 {
	if x != nil {
		return x.TotalFavorites
	}
	return 0
}

var File_interaction_interaction_proto protoreflect.FileDescriptor

const file_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	"\x1dinteraction/interaction.proto\x12\vinteraction\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\bLikeItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x125\n" +
	"\bliked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\alikedAt\"\x9a\x02\n" +
	"\vCommentItem\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x122\n" +
	"\areplies\x18\b \x03(\v2\x18.interaction.CommentItemR\areplies\"\x81\x01\n" +
	"\fFavoriteItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12=\n" +
	"\ffavorited_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vfavoritedAt\"F\n" +
	"\x10LikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"*\n" +
	"\x0eLikeVideoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x12UnlikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\",\n" +
	"\x10UnlikeVideoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x18GetVideoLikeCountRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"7\n" +
	"\x16GetVideoLikeCountReply\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\"\x7f\n" +
	"\x12PostCommentRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\"F\n" +
	"\x10PostCommentReply\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.interaction.CommentItemR\acomment\"\x90\x01\n" +
	"\x13ListCommentsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12&\n" +
	"\x0froot_comment_id\x18\x04 \x01(\x03R\rrootCommentId\"\x91\x01\n" +
	"\x11ListCommentsReply\x124\n" +
	"\bcomments\x18\x01 \x03(\v2\x18.interaction.CommentItemR\bcomments\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12%\n" +
	"\x0etotal_comments\x18\x03 \x01(\x03R\rtotalComments\"J\n" +
	"\x14FavoriteVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\".\n" +
	"\x12FavoriteVideoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x16UnfavoriteVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"0\n" +
	"\x14UnfavoriteVideoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x14ListFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x97\x01\n" +
	"\x12ListFavoritesReply\x127\n" +
	"\tfavorites\x18\x01 \x03(\v2\x19.interaction.FavoriteItemR\tfavorites\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12'\n" +
	"\x0ftotal_favorites\x18\x03 \x01(\x03R\x0etotalFavorites2\x8b\b\n" +
	"\x12InteractionService\x12k\n" +
	"\tLikeVideo\x12\x1d.interaction.LikeVideoRequest\x1a\x1b.interaction.LikeVideoReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/interaction/video/like\x12s\n" +
	"\vUnlikeVideo\x12\x1f.interaction.UnlikeVideoRequest\x1a\x1d.interaction.UnlikeVideoReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/interaction/video/unlike\x12\x91\x01\n" +
	"\x11GetVideoLikeCount\x12%.interaction.GetVideoLikeCountRequest\x1a#.interaction.GetVideoLikeCountReply\"0\x82\xd3\xe4\x93\x02*\x12(/interaction/video/{video_id}/like_count\x12t\n" +
	"\vPostComment\x12\x1f.interaction.PostCommentRequest\x1a\x1d.interaction.PostCommentReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/interaction/video/comment\x12\x80\x01\n" +
	"\fListComments\x12 .interaction.ListCommentsRequest\x1a\x1e.interaction.ListCommentsReply\".\x82\xd3\xe4\x93\x02(\x12&/interaction/video/{video_id}/comments\x12{\n" +
	"\rFavoriteVideo\x12!.interaction.FavoriteVideoRequest\x1a\x1f.interaction.FavoriteVideoReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/interaction/video/favorite\x12\x83\x01\n" +
	"\x0fUnfavoriteVideo\x12#.interaction.UnfavoriteVideoRequest\x1a!.interaction.UnfavoriteVideoReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/interaction/video/unfavorite\x12\x82\x01\n" +
	"\rListFavorites\x12!.interaction.ListFavoritesRequest\x1a\x1f.interaction.ListFavoritesReply\"-\x82\xd3\xe4\x93\x02'\x12%/interaction/user/{user_id}/favoritesB)Z'interaction/api/interaction;interactionb\x06proto3"

var (
	file_interaction_interaction_proto_rawDescOnce sync.Once
	file_interaction_interaction_proto_rawDescData []byte
)

func file_interaction_interaction_proto_rawDescGZIP() []byte {
	file_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_interaction_proto_rawDesc), len(file_interaction_interaction_proto_rawDesc)))
	})
	return file_interaction_interaction_proto_rawDescData
}

var file_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_interaction_interaction_proto_goTypes = []any{
	(*LikeItem)(nil),                 // 0: interaction.LikeItem
	(*CommentItem)(nil),              // 1: interaction.CommentItem
	(*FavoriteItem)(nil),             // 2: interaction.FavoriteItem
	(*LikeVideoRequest)(nil),         // 3: interaction.LikeVideoRequest
	(*LikeVideoReply)(nil),           // 4: interaction.LikeVideoReply
	(*UnlikeVideoRequest)(nil),       // 5: interaction.UnlikeVideoRequest
	(*UnlikeVideoReply)(nil),         // 6: interaction.UnlikeVideoReply
	(*GetVideoLikeCountRequest)(nil), // 7: interaction.GetVideoLikeCountRequest
	(*GetVideoLikeCountReply)(nil),   // 8: interaction.GetVideoLikeCountReply
	(*PostCommentRequest)(nil),       // 9: interaction.PostCommentRequest
	(*PostCommentReply)(nil),         // 10: interaction.PostCommentReply
	(*ListCommentsRequest)(nil),      // 11: interaction.ListCommentsRequest
	(*ListCommentsReply)(nil),        // 12: interaction.ListCommentsReply
	(*FavoriteVideoRequest)(nil),     // 13: interaction.FavoriteVideoRequest
	(*FavoriteVideoReply)(nil),       // 14: interaction.FavoriteVideoReply
	(*UnfavoriteVideoRequest)(nil),   // 15: interaction.UnfavoriteVideoRequest
	(*UnfavoriteVideoReply)(nil),     // 16: interaction.UnfavoriteVideoReply
	(*ListFavoritesRequest)(nil),     // 17: interaction.ListFavoritesRequest
	(*ListFavoritesReply)(nil),       // 18: interaction.ListFavoritesReply
	(*timestamppb.Timestamp)(nil),    // 19: google.protobuf.Timestamp
}
var file_interaction_interaction_proto_depIdxs = []int32{
	19, // 0: interaction.LikeItem.liked_at:type_name -> google.protobuf.Timestamp
	19, // 1: interaction.CommentItem.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: interaction.CommentItem.replies:type_name -> interaction.CommentItem
	19, // 3: interaction.FavoriteItem.favorited_at:type_name -> google.protobuf.Timestamp
	1,  // 4: interaction.PostCommentReply.comment:type_name -> interaction.CommentItem
	1,  // 5: interaction.ListCommentsReply.comments:type_name -> interaction.CommentItem
	2,  // 6: interaction.ListFavoritesReply.favorites:type_name -> interaction.FavoriteItem
	3,  // 7: interaction.InteractionService.LikeVideo:input_type -> interaction.LikeVideoRequest
	5,  // 8: interaction.InteractionService.UnlikeVideo:input_type -> interaction.UnlikeVideoRequest
	7,  // 9: interaction.InteractionService.GetVideoLikeCount:input_type -> interaction.GetVideoLikeCountRequest
	9,  // 10: interaction.InteractionService.PostComment:input_type -> interaction.PostCommentRequest
	11, // 11: interaction.InteractionService.ListComments:input_type -> interaction.ListCommentsRequest
	13, // 12: interaction.InteractionService.FavoriteVideo:input_type -> interaction.FavoriteVideoRequest
	15, // 13: interaction.InteractionService.UnfavoriteVideo:input_type -> interaction.UnfavoriteVideoRequest
	17, // 14: interaction.InteractionService.ListFavorites:input_type -> interaction.ListFavoritesRequest
	4,  // 15: interaction.InteractionService.LikeVideo:output_type -> interaction.LikeVideoReply
	6,  // 16: interaction.InteractionService.UnlikeVideo:output_type -> interaction.UnlikeVideoReply
	8,  // 17: interaction.InteractionService.GetVideoLikeCount:output_type -> interaction.GetVideoLikeCountReply
	10, // 18: interaction.InteractionService.PostComment:output_type -> interaction.PostCommentReply
	12, // 19: interaction.InteractionService.ListComments:output_type -> interaction.ListCommentsReply
	14, // 20: interaction.InteractionService.FavoriteVideo:output_type -> interaction.FavoriteVideoReply
	16, // 21: interaction.InteractionService.UnfavoriteVideo:output_type -> interaction.UnfavoriteVideoReply
	18, // 22: interaction.InteractionService.ListFavorites:output_type -> interaction.ListFavoritesReply
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_interaction_interaction_proto_init() }
func file_interaction_interaction_proto_init() {
	if File_interaction_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_interaction_proto_rawDesc), len(file_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_interaction_proto_msgTypes,
	}.Build()
	File_interaction_interaction_proto = out.File
	file_interaction_interaction_proto_goTypes = nil
	file_interaction_interaction_proto_depIdxs = nil
}
