// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"video/internal/biz"
	"video/internal/conf"
	"video/internal/data"
	"video/internal/pkg/registry"
	"video/internal/server"
	"video/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	kafkaProducer := data.NewKafkaProducer(dataData, logger)
	videoRepo := data.NewVideoRepo(dataData, logger, kafkaProducer)
	videoUsecase := biz.NewVideoUsecase(videoRepo, logger)
	videoService := service.NewVideoService(videoUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, videoService, logger)
	httpServer := server.NewHTTPServer(confServer, videoService, logger)
	registrar := registry.NewRegistry(confRegistry, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
